Dev
prefabsprout/VCF_web pull request #1
Opened 2020-05-02 19:14 UTC by prefabsprout

2020-05-06 08:46 UTC, AleksandrSl commented
Можешь убрать папку build ? В плане удалить ее вообще из репозитория. Эти файлы можно локально получить всегда собрав у себя проект, их не надо в репозиторий помещать. Можешь создать `.gitignore` стандартный с помощью плагина в IDEA. Указав там что у тебя проект на Gradle в среде разработки JetBrains и все что он в себя включает из репозитория можно убрать. (Локально в директории эти файлы будут лежать, естественно)

2020-05-06 09:06 UTC, AleksandrSl requested changes

2020-05-06 09:06 UTC, AleksandrSl commented on src/db_factory.kt
> +    val left_boundary: Column<Int> = integer("left_boundary")
А какие границы у `Int` по размеру?

2020-05-06 09:06 UTC, AleksandrSl commented on src/db_factory.kt
> +object VCF_data : Table() {
Можешь еще на `IdTable` посмотреть

2020-05-06 09:06 UTC, AleksandrSl commented on src/db_factory.kt
> +    val rs: Column<String> = varchar("rs", 40)
А просто типа text не бывает? По какой причине ты решил так все соптимизировать использовав varchar?

2020-05-06 09:06 UTC, AleksandrSl commented on src/Application.kt
> +    Database.connect("jdbc:mysql://localhost:3306/vcf", driver = "com.mysql.jdbc.Driver",
Всякие адреса базы и пароли лучше в конфигурацию выносить.

2020-05-06 09:06 UTC, AleksandrSl commented on src/Application.kt
> +        post {
А почему ты выбрал post?

2020-05-06 09:06 UTC, AleksandrSl commented on src/Application.kt
> +                            (VCF_data.left_boundary eq (post["left_boundary"]?.toInt() ?: 0)) and
А ты уверен, что если тебе прислали неверный запрос, то есть запрос, без этого поля вообще, стоит что=-то возвращать, а не вернуть какой нибудь 400 Bad Request

2020-05-06 09:06 UTC, AleksandrSl commented on src/Application.kt
> +            else if (res.isEmpty()){
Есть ощущение, что это условие и условие сверху полностью друг друга дополняют, в том плане, что если верно первое неверно второе, и наоборот тоже, и не бывает что оба неверны. Если это так, то можно избавиться от второго `if`

2020-05-06 09:06 UTC, AleksandrSl commented on src/Application.kt
> +                call.respondText("Oops! Looks like we're not found your annotation.",
Давай ответы будем возвращать в виде json, если что-то нашлось, в противном  случае возвращать не 200, а какой-нибудь подходящий статус

2020-05-06 09:06 UTC, AleksandrSl commented on src/Application.kt
> +    Database.connect("jdbc:mysql://localhost:3306/vcf", driver = "com.mysql.jdbc.Driver",
Просто оставлю это тут- tabix (не тот, который у яндекса)

2020-05-06 13:11 UTC, prefabsprout commented on src/db_factory.kt
> +    val left_boundary: Column<Int> = integer("left_boundary")
Гугл говорит, что от -2,147,483,64 до 2,147,483,647. А что?

2020-05-06 13:11 UTC, prefabsprout commented on src/db_factory.kt
> +    val rs: Column<String> = varchar("rs", 40)
Насколько я понял, у varchar есть ограничение на длину вводимой строки. В случае rs, например, это может быть критично. Думаю, не очень красиво будет увидеть какой-то неадекватно длинный rs. Хотя я и без того, наверное, слишком большое ограничение задал на это поле. 
С nucleotide руководствовался примерно теми же мыслями. Сейчас думаю, что, вероятно, это и впрямь не очень осмысленно.

2020-05-06 13:11 UTC, prefabsprout commented on src/Application.kt
> +    Database.connect("jdbc:mysql://localhost:3306/vcf", driver = "com.mysql.jdbc.Driver",
Понял-принял, попробую это исправить.

2020-05-06 13:11 UTC, prefabsprout commented on src/Application.kt
> +        post {
Потому что приложение - это форма ввода данных. И мы постим запрос на сервер. Вроде как можно всё равно использовать get в данной ситуации и результат будет одинаковый, но мне показалось, что в данном контексте post более уместен.

2020-05-06 13:11 UTC, prefabsprout commented on src/Application.kt
> +                            (VCF_data.left_boundary eq (post["left_boundary"]?.toInt() ?: 0)) and
Не уверен. Посмотрю, что с этим можно сделать.

2020-05-06 13:12 UTC, prefabsprout commented on src/Application.kt
> +    Database.connect("jdbc:mysql://localhost:3306/vcf", driver = "com.mysql.jdbc.Driver",
Если честно, я решительно не понял, как с ним работать. Попытка прочесть файл, чтобы понять, как с ним быть, не привела ни к чему. То же касается попыток заглянуть в спецификацию. Потому я подумал, что лучше будет залить данные в MySQL базу данных и попытаться проиндексировать их там.

2020-05-08 08:10 UTC, AleksandrSl commented on src/Application.kt
> +        post {
Тем не менее основная цель получить данные с сервера, поэтому с точки зрения API это скорее GET. тем более если не видеть того, что это нам какая-то форма отправляет данные.

2020-05-08 08:15 UTC, AleksandrSl commented on src/db_factory.kt
> +    val left_boundary: Column<Int> = integer("left_boundary")
Справедливо, какие-то флэшбэки из паскаля, где int был в 65 тысяч с чем-то максимум, тогда бы не все координаты влезли

2020-05-08 08:17 UTC, AleksandrSl commented on src/Application.kt
> +    Database.connect("jdbc:mysql://localhost:3306/vcf", driver = "com.mysql.jdbc.Driver",
Стоит погуглить, есть ли какие-то бибилотеки для работы с файлами и его индексами из Java (спойлер: такая есть)

2020-05-08 08:20 UTC, AleksandrSl commented on src/Application.kt
> +                post["left_boundary"].toString().isEmpty() ||
А эти результаты `post["left_boundary"]` разве не Nullable? Тогда можно просто проверить null там или нет, не придется конвертировать в строку лишний раз

2020-05-08 08:37 UTC, AleksandrSl commented on src/Application.kt
> +                            (VCF_data.left_boundary eq (post["left_boundary"]?.toInt() ?: 0)) and
Здесь, теперь можно это убрать, сюда гарантированно придут не null, так как у тебя выше условие есть для проверки этого

2020-05-08 09:08 UTC, AleksandrSl commented on README.md
> +```CREATE UNIQUE INDEX id ON VCF_data (id);```
А индексы на первичные ключи по умолчанию не создаются?

2020-05-10 17:19 UTC, prefabsprout commented on README.md
> +```CREATE UNIQUE INDEX id ON VCF_data (id);```
Не уверен. Потому решил тогда, на всякий случай, сделать это.

2020-05-12 11:58 UTC, nopechucktesta commented on src/Application.kt
> +                    .readLine()
А нам тут точно всегда достаточно взять единственный hit из query?

2020-05-12 16:31 UTC, prefabsprout commented on src/Application.kt
> +                    .readLine()
Учтено и исправлено.

2020-09-11 10:21 UTC, merged